import {
  Bell,
  Building2,
  DatabaseBackup,
  FileText,
  ClipboardList,
  Languages,
  Ruler,
  Timer,
  WalletCards,
} from "lucide-react";
import type { HeloraSettings, SettingsCategory } from "../types/settings.types";

export const settingsCategories: SettingsCategory[] = [
  {
    id: "business",
    title: "Business Profile",
    description: "Shop name, address, contact details, and opening hours.",
    badge: "Basic",
    icon: Building2,
  },
  {
    id: "orders",
    title: "Order Settings",
    description: "Order numbers, promised days, urgent orders, and notes.",
    badge: "Orders",
    icon: ClipboardList,
  },
  {
    id: "measurements",
    title: "Measurement Settings",
    description: "Measurement unit, verification, and old measurement warnings.",
    badge: "Tailoring",
    icon: Ruler,
  },
  {
    id: "attendance",
    title: "Attendance Settings",
    description: "Work time, late grace, overtime, and approval rules.",
    badge: "Employees",
    icon: Timer,
  },
  {
    id: "prints",
    title: "Print Settings",
    description: "Customer receipts, tailor copies, headers, and print size.",
    badge: "Documents",
    icon: FileText,
  },
  {
    id: "whatsapp",
    title: "WhatsApp Settings",
    description: "Order updates, payment messages, and message templates.",
    badge: "Messages",
    icon: Bell,
  },
  {
    id: "payments",
    title: "Payment Settings",
    description: "Advance payments, credit orders, salary, and piece-rate rules.",
    badge: "Money",
    icon: WalletCards,
  },
  {
    id: "dataImport",
    title: "Data Import",
    description: "Customer, block, measurement, and employee import rules.",
    badge: "Migration",
    icon: DatabaseBackup,
  },
  {
    id: "preferences",
    title: "System Preferences",
    description: "Language, date format, time format, theme, and page size.",
    badge: "System",
    icon: Languages,
  },
];

export const defaultHeloraSettings: HeloraSettings = {
  business: {
    shopName: "New Deepani Garment",
    phoneNumber: "0718370292",
    email: "info@helora.local",
    address: "Main Street",
    town: "Horana",
    registrationNumber: "",
    currency: "LKR",
    openingTime: "08:00",
    closingTime: "17:00",
  },
  orders: {
    orderPrefix: "ORD",
    groupOrderPrefix: "GRP",
    defaultPromisedDays: 7,
    defaultOrderSource: "Physical Shop",
    allowUrgentOrders: true,
    enableSinhalaNotes: true,
    requireAdvancePayment: false,
    hidePricesOnTailorPrint: true,
  },
  measurements: {
    measurementUnit: "Inches",
    defaultCategory: "Uniform",
    allowVersioning: true,
    requireVerification: true,
    warnAfterMonths: 6,
    showPreviousMeasurements: true,
  },
  attendance: {
    workStartTime: "08:00",
    workEndTime: "17:00",
    lateGraceMinutes: 5,
    halfDayMinimumHours: 4,
    fullDayMinimumHours: 8,
    overtimeEnabled: true,
    overtimeStartsAfter: "17:00",
    attendanceApprovalRequired: true,
    deviceAttendanceEnabled: true,
    manualAttendanceAllowed: true,
  },
  prints: {
    defaultPrintSize: "A4",
    showShopHeader: true,
    showFooter: true,
    tailorPrintSize: "Half A4",
    showOrderNotes: true,
    showMeasurementNotes: true,
    showItemNotesWhenAvailable: true,
    showCustomerPhone: true,
    showPricesOnCustomerReceipt: true,
    hidePricesOnTailorCopy: true,
  },
  whatsapp: {
    enabled: false,
    businessPhoneNumber: "",
    sendOrderCreatedMessage: true,
    sendOrderReadyMessage: true,
    sendPaymentReceivedMessage: true,
    orderCreatedTemplate:
      "Hello {{customerName}}, your order {{orderNumber}} has been created.",
    orderReadyTemplate:
      "Hello {{customerName}}, your order {{orderNumber}} is ready for pickup.",
    paymentReceivedTemplate:
      "Hello {{customerName}}, payment received for order {{orderNumber}}.",
  },
  payments: {
    advancePaymentEnabled: true,
    minimumAdvancePercentage: 30,
    allowCreditOrders: true,
    defaultPaymentMethod: "Cash",
    receiptPrefix: "RCT",
    monthlySalaryEnabled: true,
    dailyPaymentEnabled: true,
    pieceRatePaymentEnabled: true,
    overtimeRateMultiplier: 1.5,
    lateDeductionEnabled: false,
  },
  dataImport: {
    allowDuplicatePhoneNumbers: false,
    autoGenerateCustomerNumbers: true,
    autoGenerateBlockNumbers: true,
    validateBeforeImport: true,
    keepImportHistory: true,
  },
  preferences: {
    language: "English",
    dateFormat: "dd MMM yyyy",
    timeFormat: "12-hour",
    defaultPageSize: 10,
    defaultDashboardRange: "This month",
    theme: "System",
  },
};