/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R403RouteImport } from './routes/403'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authActivateAccountRouteImport } from './routes/(auth)/activate-account'
import { Route as AuthenticatedAdminUsersRouteRouteImport } from './routes/_authenticated/admin/users/route'
import { Route as AuthenticatedAppSupportIndexRouteImport } from './routes/_authenticated/app/support/index'
import { Route as AuthenticatedAppProfileIndexRouteImport } from './routes/_authenticated/app/profile/index'
import { Route as AuthenticatedAppOrdersIndexRouteImport } from './routes/_authenticated/app/orders/index'
import { Route as AuthenticatedAppInvoicesIndexRouteImport } from './routes/_authenticated/app/invoices/index'
import { Route as AuthenticatedAppDashboardIndexRouteImport } from './routes/_authenticated/app/dashboard/index'
import { Route as AuthenticatedAppAccountIndexRouteImport } from './routes/_authenticated/app/account/index'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin/settings/index'
import { Route as AuthenticatedAdminRolePermissionsIndexRouteImport } from './routes/_authenticated/admin/role-permissions/index'
import { Route as AuthenticatedAdminPendingIndexRouteImport } from './routes/_authenticated/admin/pending/index'
import { Route as AuthenticatedAdminDashboardIndexRouteImport } from './routes/_authenticated/admin/dashboard/index'
import { Route as AuthenticatedAdminActivityLogIndexRouteImport } from './routes/_authenticated/admin/activity-log/index'

const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authActivateAccountRoute = authActivateAccountRouteImport.update({
  id: '/(auth)/activate-account',
  path: '/activate-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRouteRoute =
  AuthenticatedAdminUsersRouteRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSupportIndexRoute =
  AuthenticatedAppSupportIndexRouteImport.update({
    id: '/app/support/',
    path: '/app/support/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProfileIndexRoute =
  AuthenticatedAppProfileIndexRouteImport.update({
    id: '/app/profile/',
    path: '/app/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppOrdersIndexRoute =
  AuthenticatedAppOrdersIndexRouteImport.update({
    id: '/app/orders/',
    path: '/app/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppInvoicesIndexRoute =
  AuthenticatedAppInvoicesIndexRouteImport.update({
    id: '/app/invoices/',
    path: '/app/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDashboardIndexRoute =
  AuthenticatedAppDashboardIndexRouteImport.update({
    id: '/app/dashboard/',
    path: '/app/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAccountIndexRoute =
  AuthenticatedAppAccountIndexRouteImport.update({
    id: '/app/account/',
    path: '/app/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/admin/settings/',
    path: '/admin/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolePermissionsIndexRoute =
  AuthenticatedAdminRolePermissionsIndexRouteImport.update({
    id: '/admin/role-permissions/',
    path: '/admin/role-permissions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPendingIndexRoute =
  AuthenticatedAdminPendingIndexRouteImport.update({
    id: '/admin/pending/',
    path: '/admin/pending/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardIndexRoute =
  AuthenticatedAdminDashboardIndexRouteImport.update({
    id: '/admin/dashboard/',
    path: '/admin/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminActivityLogIndexRoute =
  AuthenticatedAdminActivityLogIndexRouteImport.update({
    id: '/admin/activity-log/',
    path: '/admin/activity-log/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/activate-account': typeof authActivateAccountRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteRoute
  '/admin/activity-log/': typeof AuthenticatedAdminActivityLogIndexRoute
  '/admin/dashboard/': typeof AuthenticatedAdminDashboardIndexRoute
  '/admin/pending/': typeof AuthenticatedAdminPendingIndexRoute
  '/admin/role-permissions/': typeof AuthenticatedAdminRolePermissionsIndexRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/app/account/': typeof AuthenticatedAppAccountIndexRoute
  '/app/dashboard/': typeof AuthenticatedAppDashboardIndexRoute
  '/app/invoices/': typeof AuthenticatedAppInvoicesIndexRoute
  '/app/orders/': typeof AuthenticatedAppOrdersIndexRoute
  '/app/profile/': typeof AuthenticatedAppProfileIndexRoute
  '/app/support/': typeof AuthenticatedAppSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/activate-account': typeof authActivateAccountRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteRoute
  '/admin/activity-log': typeof AuthenticatedAdminActivityLogIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardIndexRoute
  '/admin/pending': typeof AuthenticatedAdminPendingIndexRoute
  '/admin/role-permissions': typeof AuthenticatedAdminRolePermissionsIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/app/account': typeof AuthenticatedAppAccountIndexRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardIndexRoute
  '/app/invoices': typeof AuthenticatedAppInvoicesIndexRoute
  '/app/orders': typeof AuthenticatedAppOrdersIndexRoute
  '/app/profile': typeof AuthenticatedAppProfileIndexRoute
  '/app/support': typeof AuthenticatedAppSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/403': typeof R403Route
  '/(auth)/activate-account': typeof authActivateAccountRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteRoute
  '/_authenticated/admin/activity-log/': typeof AuthenticatedAdminActivityLogIndexRoute
  '/_authenticated/admin/dashboard/': typeof AuthenticatedAdminDashboardIndexRoute
  '/_authenticated/admin/pending/': typeof AuthenticatedAdminPendingIndexRoute
  '/_authenticated/admin/role-permissions/': typeof AuthenticatedAdminRolePermissionsIndexRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/_authenticated/app/account/': typeof AuthenticatedAppAccountIndexRoute
  '/_authenticated/app/dashboard/': typeof AuthenticatedAppDashboardIndexRoute
  '/_authenticated/app/invoices/': typeof AuthenticatedAppInvoicesIndexRoute
  '/_authenticated/app/orders/': typeof AuthenticatedAppOrdersIndexRoute
  '/_authenticated/app/profile/': typeof AuthenticatedAppProfileIndexRoute
  '/_authenticated/app/support/': typeof AuthenticatedAppSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/activate-account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/users'
    | '/admin/activity-log/'
    | '/admin/dashboard/'
    | '/admin/pending/'
    | '/admin/role-permissions/'
    | '/admin/settings/'
    | '/app/account/'
    | '/app/dashboard/'
    | '/app/invoices/'
    | '/app/orders/'
    | '/app/profile/'
    | '/app/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/activate-account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/users'
    | '/admin/activity-log'
    | '/admin/dashboard'
    | '/admin/pending'
    | '/admin/role-permissions'
    | '/admin/settings'
    | '/app/account'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/orders'
    | '/app/profile'
    | '/app/support'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/403'
    | '/(auth)/activate-account'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/activity-log/'
    | '/_authenticated/admin/dashboard/'
    | '/_authenticated/admin/pending/'
    | '/_authenticated/admin/role-permissions/'
    | '/_authenticated/admin/settings/'
    | '/_authenticated/app/account/'
    | '/_authenticated/app/dashboard/'
    | '/_authenticated/app/invoices/'
    | '/_authenticated/app/orders/'
    | '/_authenticated/app/profile/'
    | '/_authenticated/app/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R403Route: typeof R403Route
  authActivateAccountRoute: typeof authActivateAccountRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/activate-account': {
      id: '/(auth)/activate-account'
      path: '/activate-account'
      fullPath: '/activate-account'
      preLoaderRoute: typeof authActivateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/support/': {
      id: '/_authenticated/app/support/'
      path: '/app/support'
      fullPath: '/app/support/'
      preLoaderRoute: typeof AuthenticatedAppSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profile/': {
      id: '/_authenticated/app/profile/'
      path: '/app/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AuthenticatedAppProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/orders/': {
      id: '/_authenticated/app/orders/'
      path: '/app/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AuthenticatedAppOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/invoices/': {
      id: '/_authenticated/app/invoices/'
      path: '/app/invoices'
      fullPath: '/app/invoices/'
      preLoaderRoute: typeof AuthenticatedAppInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dashboard/': {
      id: '/_authenticated/app/dashboard/'
      path: '/app/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AuthenticatedAppDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/account/': {
      id: '/_authenticated/app/account/'
      path: '/app/account'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AuthenticatedAppAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/role-permissions/': {
      id: '/_authenticated/admin/role-permissions/'
      path: '/admin/role-permissions'
      fullPath: '/admin/role-permissions/'
      preLoaderRoute: typeof AuthenticatedAdminRolePermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pending/': {
      id: '/_authenticated/admin/pending/'
      path: '/admin/pending'
      fullPath: '/admin/pending/'
      preLoaderRoute: typeof AuthenticatedAdminPendingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard/': {
      id: '/_authenticated/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AuthenticatedAdminDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/activity-log/': {
      id: '/_authenticated/admin/activity-log/'
      path: '/admin/activity-log'
      fullPath: '/admin/activity-log/'
      preLoaderRoute: typeof AuthenticatedAdminActivityLogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminUsersRouteRoute: typeof AuthenticatedAdminUsersRouteRoute
  AuthenticatedAdminActivityLogIndexRoute: typeof AuthenticatedAdminActivityLogIndexRoute
  AuthenticatedAdminDashboardIndexRoute: typeof AuthenticatedAdminDashboardIndexRoute
  AuthenticatedAdminPendingIndexRoute: typeof AuthenticatedAdminPendingIndexRoute
  AuthenticatedAdminRolePermissionsIndexRoute: typeof AuthenticatedAdminRolePermissionsIndexRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
  AuthenticatedAppAccountIndexRoute: typeof AuthenticatedAppAccountIndexRoute
  AuthenticatedAppDashboardIndexRoute: typeof AuthenticatedAppDashboardIndexRoute
  AuthenticatedAppInvoicesIndexRoute: typeof AuthenticatedAppInvoicesIndexRoute
  AuthenticatedAppOrdersIndexRoute: typeof AuthenticatedAppOrdersIndexRoute
  AuthenticatedAppProfileIndexRoute: typeof AuthenticatedAppProfileIndexRoute
  AuthenticatedAppSupportIndexRoute: typeof AuthenticatedAppSupportIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminUsersRouteRoute: AuthenticatedAdminUsersRouteRoute,
  AuthenticatedAdminActivityLogIndexRoute:
    AuthenticatedAdminActivityLogIndexRoute,
  AuthenticatedAdminDashboardIndexRoute: AuthenticatedAdminDashboardIndexRoute,
  AuthenticatedAdminPendingIndexRoute: AuthenticatedAdminPendingIndexRoute,
  AuthenticatedAdminRolePermissionsIndexRoute:
    AuthenticatedAdminRolePermissionsIndexRoute,
  AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
  AuthenticatedAppAccountIndexRoute: AuthenticatedAppAccountIndexRoute,
  AuthenticatedAppDashboardIndexRoute: AuthenticatedAppDashboardIndexRoute,
  AuthenticatedAppInvoicesIndexRoute: AuthenticatedAppInvoicesIndexRoute,
  AuthenticatedAppOrdersIndexRoute: AuthenticatedAppOrdersIndexRoute,
  AuthenticatedAppProfileIndexRoute: AuthenticatedAppProfileIndexRoute,
  AuthenticatedAppSupportIndexRoute: AuthenticatedAppSupportIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R403Route: R403Route,
  authActivateAccountRoute: authActivateAccountRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
