/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R403RouteImport } from './routes/403'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authActivateAccountRouteImport } from './routes/(auth)/activate-account'
import { Route as AuthenticatedAppWhatsappRouteRouteImport } from './routes/_authenticated/app/whatsapp/route'
import { Route as AuthenticatedAppUsersRouteRouteImport } from './routes/_authenticated/app/users/route'
import { Route as AuthenticatedAppMeasurementsRouteRouteImport } from './routes/_authenticated/app/measurements/route'
import { Route as AuthenticatedAppCategoryRouteRouteImport } from './routes/_authenticated/app/category/route'
import { Route as AuthenticatedAppSupportIndexRouteImport } from './routes/_authenticated/app/support/index'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated/app/settings/index'
import { Route as AuthenticatedAppRolePermissionIndexRouteImport } from './routes/_authenticated/app/role-permission/index'
import { Route as AuthenticatedAppProfileIndexRouteImport } from './routes/_authenticated/app/profile/index'
import { Route as AuthenticatedAppOrdersIndexRouteImport } from './routes/_authenticated/app/orders/index'
import { Route as AuthenticatedAppGroupOrdersIndexRouteImport } from './routes/_authenticated/app/group-orders/index'
import { Route as AuthenticatedAppEmployeesIndexRouteImport } from './routes/_authenticated/app/employees/index'
import { Route as AuthenticatedAppDashboardIndexRouteImport } from './routes/_authenticated/app/dashboard/index'
import { Route as AuthenticatedAppCustomersIndexRouteImport } from './routes/_authenticated/app/customers/index'
import { Route as AuthenticatedAppBlocksIndexRouteImport } from './routes/_authenticated/app/blocks/index'
import { Route as AuthenticatedAppAttendanceIndexRouteImport } from './routes/_authenticated/app/attendance/index'
import { Route as AuthenticatedAppAccountIndexRouteImport } from './routes/_authenticated/app/account/index'
import { Route as AuthenticatedAdminPendingIndexRouteImport } from './routes/_authenticated/admin/pending/index'
import { Route as AuthenticatedAdminDashboardIndexRouteImport } from './routes/_authenticated/admin/dashboard/index'
import { Route as AuthenticatedAdminActivityLogIndexRouteImport } from './routes/_authenticated/admin/activity-log/index'
import { Route as AuthenticatedAppGroupOrdersGroupOrderIdRouteImport } from './routes/_authenticated/app/group-orders/$groupOrderId'

const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authActivateAccountRoute = authActivateAccountRouteImport.update({
  id: '/(auth)/activate-account',
  path: '/activate-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWhatsappRouteRoute =
  AuthenticatedAppWhatsappRouteRouteImport.update({
    id: '/app/whatsapp',
    path: '/app/whatsapp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppUsersRouteRoute =
  AuthenticatedAppUsersRouteRouteImport.update({
    id: '/app/users',
    path: '/app/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMeasurementsRouteRoute =
  AuthenticatedAppMeasurementsRouteRouteImport.update({
    id: '/app/measurements',
    path: '/app/measurements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCategoryRouteRoute =
  AuthenticatedAppCategoryRouteRouteImport.update({
    id: '/app/category',
    path: '/app/category',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSupportIndexRoute =
  AuthenticatedAppSupportIndexRouteImport.update({
    id: '/app/support/',
    path: '/app/support/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/app/settings/',
    path: '/app/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRolePermissionIndexRoute =
  AuthenticatedAppRolePermissionIndexRouteImport.update({
    id: '/app/role-permission/',
    path: '/app/role-permission/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProfileIndexRoute =
  AuthenticatedAppProfileIndexRouteImport.update({
    id: '/app/profile/',
    path: '/app/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppOrdersIndexRoute =
  AuthenticatedAppOrdersIndexRouteImport.update({
    id: '/app/orders/',
    path: '/app/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppGroupOrdersIndexRoute =
  AuthenticatedAppGroupOrdersIndexRouteImport.update({
    id: '/app/group-orders/',
    path: '/app/group-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppEmployeesIndexRoute =
  AuthenticatedAppEmployeesIndexRouteImport.update({
    id: '/app/employees/',
    path: '/app/employees/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDashboardIndexRoute =
  AuthenticatedAppDashboardIndexRouteImport.update({
    id: '/app/dashboard/',
    path: '/app/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCustomersIndexRoute =
  AuthenticatedAppCustomersIndexRouteImport.update({
    id: '/app/customers/',
    path: '/app/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBlocksIndexRoute =
  AuthenticatedAppBlocksIndexRouteImport.update({
    id: '/app/blocks/',
    path: '/app/blocks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAttendanceIndexRoute =
  AuthenticatedAppAttendanceIndexRouteImport.update({
    id: '/app/attendance/',
    path: '/app/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAccountIndexRoute =
  AuthenticatedAppAccountIndexRouteImport.update({
    id: '/app/account/',
    path: '/app/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPendingIndexRoute =
  AuthenticatedAdminPendingIndexRouteImport.update({
    id: '/admin/pending/',
    path: '/admin/pending/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardIndexRoute =
  AuthenticatedAdminDashboardIndexRouteImport.update({
    id: '/admin/dashboard/',
    path: '/admin/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminActivityLogIndexRoute =
  AuthenticatedAdminActivityLogIndexRouteImport.update({
    id: '/admin/activity-log/',
    path: '/admin/activity-log/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppGroupOrdersGroupOrderIdRoute =
  AuthenticatedAppGroupOrdersGroupOrderIdRouteImport.update({
    id: '/app/group-orders/$groupOrderId',
    path: '/app/group-orders/$groupOrderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/activate-account': typeof authActivateAccountRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/app/category': typeof AuthenticatedAppCategoryRouteRoute
  '/app/measurements': typeof AuthenticatedAppMeasurementsRouteRoute
  '/app/users': typeof AuthenticatedAppUsersRouteRoute
  '/app/whatsapp': typeof AuthenticatedAppWhatsappRouteRoute
  '/app/group-orders/$groupOrderId': typeof AuthenticatedAppGroupOrdersGroupOrderIdRoute
  '/admin/activity-log/': typeof AuthenticatedAdminActivityLogIndexRoute
  '/admin/dashboard/': typeof AuthenticatedAdminDashboardIndexRoute
  '/admin/pending/': typeof AuthenticatedAdminPendingIndexRoute
  '/app/account/': typeof AuthenticatedAppAccountIndexRoute
  '/app/attendance/': typeof AuthenticatedAppAttendanceIndexRoute
  '/app/blocks/': typeof AuthenticatedAppBlocksIndexRoute
  '/app/customers/': typeof AuthenticatedAppCustomersIndexRoute
  '/app/dashboard/': typeof AuthenticatedAppDashboardIndexRoute
  '/app/employees/': typeof AuthenticatedAppEmployeesIndexRoute
  '/app/group-orders/': typeof AuthenticatedAppGroupOrdersIndexRoute
  '/app/orders/': typeof AuthenticatedAppOrdersIndexRoute
  '/app/profile/': typeof AuthenticatedAppProfileIndexRoute
  '/app/role-permission/': typeof AuthenticatedAppRolePermissionIndexRoute
  '/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/app/support/': typeof AuthenticatedAppSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/activate-account': typeof authActivateAccountRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/app/category': typeof AuthenticatedAppCategoryRouteRoute
  '/app/measurements': typeof AuthenticatedAppMeasurementsRouteRoute
  '/app/users': typeof AuthenticatedAppUsersRouteRoute
  '/app/whatsapp': typeof AuthenticatedAppWhatsappRouteRoute
  '/app/group-orders/$groupOrderId': typeof AuthenticatedAppGroupOrdersGroupOrderIdRoute
  '/admin/activity-log': typeof AuthenticatedAdminActivityLogIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardIndexRoute
  '/admin/pending': typeof AuthenticatedAdminPendingIndexRoute
  '/app/account': typeof AuthenticatedAppAccountIndexRoute
  '/app/attendance': typeof AuthenticatedAppAttendanceIndexRoute
  '/app/blocks': typeof AuthenticatedAppBlocksIndexRoute
  '/app/customers': typeof AuthenticatedAppCustomersIndexRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardIndexRoute
  '/app/employees': typeof AuthenticatedAppEmployeesIndexRoute
  '/app/group-orders': typeof AuthenticatedAppGroupOrdersIndexRoute
  '/app/orders': typeof AuthenticatedAppOrdersIndexRoute
  '/app/profile': typeof AuthenticatedAppProfileIndexRoute
  '/app/role-permission': typeof AuthenticatedAppRolePermissionIndexRoute
  '/app/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/app/support': typeof AuthenticatedAppSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/403': typeof R403Route
  '/(auth)/activate-account': typeof authActivateAccountRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/_authenticated/app/category': typeof AuthenticatedAppCategoryRouteRoute
  '/_authenticated/app/measurements': typeof AuthenticatedAppMeasurementsRouteRoute
  '/_authenticated/app/users': typeof AuthenticatedAppUsersRouteRoute
  '/_authenticated/app/whatsapp': typeof AuthenticatedAppWhatsappRouteRoute
  '/_authenticated/app/group-orders/$groupOrderId': typeof AuthenticatedAppGroupOrdersGroupOrderIdRoute
  '/_authenticated/admin/activity-log/': typeof AuthenticatedAdminActivityLogIndexRoute
  '/_authenticated/admin/dashboard/': typeof AuthenticatedAdminDashboardIndexRoute
  '/_authenticated/admin/pending/': typeof AuthenticatedAdminPendingIndexRoute
  '/_authenticated/app/account/': typeof AuthenticatedAppAccountIndexRoute
  '/_authenticated/app/attendance/': typeof AuthenticatedAppAttendanceIndexRoute
  '/_authenticated/app/blocks/': typeof AuthenticatedAppBlocksIndexRoute
  '/_authenticated/app/customers/': typeof AuthenticatedAppCustomersIndexRoute
  '/_authenticated/app/dashboard/': typeof AuthenticatedAppDashboardIndexRoute
  '/_authenticated/app/employees/': typeof AuthenticatedAppEmployeesIndexRoute
  '/_authenticated/app/group-orders/': typeof AuthenticatedAppGroupOrdersIndexRoute
  '/_authenticated/app/orders/': typeof AuthenticatedAppOrdersIndexRoute
  '/_authenticated/app/profile/': typeof AuthenticatedAppProfileIndexRoute
  '/_authenticated/app/role-permission/': typeof AuthenticatedAppRolePermissionIndexRoute
  '/_authenticated/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/app/support/': typeof AuthenticatedAppSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/activate-account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app/category'
    | '/app/measurements'
    | '/app/users'
    | '/app/whatsapp'
    | '/app/group-orders/$groupOrderId'
    | '/admin/activity-log/'
    | '/admin/dashboard/'
    | '/admin/pending/'
    | '/app/account/'
    | '/app/attendance/'
    | '/app/blocks/'
    | '/app/customers/'
    | '/app/dashboard/'
    | '/app/employees/'
    | '/app/group-orders/'
    | '/app/orders/'
    | '/app/profile/'
    | '/app/role-permission/'
    | '/app/settings/'
    | '/app/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/activate-account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app/category'
    | '/app/measurements'
    | '/app/users'
    | '/app/whatsapp'
    | '/app/group-orders/$groupOrderId'
    | '/admin/activity-log'
    | '/admin/dashboard'
    | '/admin/pending'
    | '/app/account'
    | '/app/attendance'
    | '/app/blocks'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/employees'
    | '/app/group-orders'
    | '/app/orders'
    | '/app/profile'
    | '/app/role-permission'
    | '/app/settings'
    | '/app/support'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/403'
    | '/(auth)/activate-account'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/_authenticated/app/category'
    | '/_authenticated/app/measurements'
    | '/_authenticated/app/users'
    | '/_authenticated/app/whatsapp'
    | '/_authenticated/app/group-orders/$groupOrderId'
    | '/_authenticated/admin/activity-log/'
    | '/_authenticated/admin/dashboard/'
    | '/_authenticated/admin/pending/'
    | '/_authenticated/app/account/'
    | '/_authenticated/app/attendance/'
    | '/_authenticated/app/blocks/'
    | '/_authenticated/app/customers/'
    | '/_authenticated/app/dashboard/'
    | '/_authenticated/app/employees/'
    | '/_authenticated/app/group-orders/'
    | '/_authenticated/app/orders/'
    | '/_authenticated/app/profile/'
    | '/_authenticated/app/role-permission/'
    | '/_authenticated/app/settings/'
    | '/_authenticated/app/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R403Route: typeof R403Route
  authActivateAccountRoute: typeof authActivateAccountRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/activate-account': {
      id: '/(auth)/activate-account'
      path: '/activate-account'
      fullPath: '/activate-account'
      preLoaderRoute: typeof authActivateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/whatsapp': {
      id: '/_authenticated/app/whatsapp'
      path: '/app/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AuthenticatedAppWhatsappRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/users': {
      id: '/_authenticated/app/users'
      path: '/app/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/measurements': {
      id: '/_authenticated/app/measurements'
      path: '/app/measurements'
      fullPath: '/app/measurements'
      preLoaderRoute: typeof AuthenticatedAppMeasurementsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/category': {
      id: '/_authenticated/app/category'
      path: '/app/category'
      fullPath: '/app/category'
      preLoaderRoute: typeof AuthenticatedAppCategoryRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/support/': {
      id: '/_authenticated/app/support/'
      path: '/app/support'
      fullPath: '/app/support/'
      preLoaderRoute: typeof AuthenticatedAppSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings/': {
      id: '/_authenticated/app/settings/'
      path: '/app/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/role-permission/': {
      id: '/_authenticated/app/role-permission/'
      path: '/app/role-permission'
      fullPath: '/app/role-permission/'
      preLoaderRoute: typeof AuthenticatedAppRolePermissionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profile/': {
      id: '/_authenticated/app/profile/'
      path: '/app/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AuthenticatedAppProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/orders/': {
      id: '/_authenticated/app/orders/'
      path: '/app/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AuthenticatedAppOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/group-orders/': {
      id: '/_authenticated/app/group-orders/'
      path: '/app/group-orders'
      fullPath: '/app/group-orders/'
      preLoaderRoute: typeof AuthenticatedAppGroupOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/employees/': {
      id: '/_authenticated/app/employees/'
      path: '/app/employees'
      fullPath: '/app/employees/'
      preLoaderRoute: typeof AuthenticatedAppEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dashboard/': {
      id: '/_authenticated/app/dashboard/'
      path: '/app/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AuthenticatedAppDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/customers/': {
      id: '/_authenticated/app/customers/'
      path: '/app/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AuthenticatedAppCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/blocks/': {
      id: '/_authenticated/app/blocks/'
      path: '/app/blocks'
      fullPath: '/app/blocks/'
      preLoaderRoute: typeof AuthenticatedAppBlocksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/attendance/': {
      id: '/_authenticated/app/attendance/'
      path: '/app/attendance'
      fullPath: '/app/attendance/'
      preLoaderRoute: typeof AuthenticatedAppAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/account/': {
      id: '/_authenticated/app/account/'
      path: '/app/account'
      fullPath: '/app/account/'
      preLoaderRoute: typeof AuthenticatedAppAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pending/': {
      id: '/_authenticated/admin/pending/'
      path: '/admin/pending'
      fullPath: '/admin/pending/'
      preLoaderRoute: typeof AuthenticatedAdminPendingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard/': {
      id: '/_authenticated/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AuthenticatedAdminDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/activity-log/': {
      id: '/_authenticated/admin/activity-log/'
      path: '/admin/activity-log'
      fullPath: '/admin/activity-log/'
      preLoaderRoute: typeof AuthenticatedAdminActivityLogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/group-orders/$groupOrderId': {
      id: '/_authenticated/app/group-orders/$groupOrderId'
      path: '/app/group-orders/$groupOrderId'
      fullPath: '/app/group-orders/$groupOrderId'
      preLoaderRoute: typeof AuthenticatedAppGroupOrdersGroupOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppCategoryRouteRoute: typeof AuthenticatedAppCategoryRouteRoute
  AuthenticatedAppMeasurementsRouteRoute: typeof AuthenticatedAppMeasurementsRouteRoute
  AuthenticatedAppUsersRouteRoute: typeof AuthenticatedAppUsersRouteRoute
  AuthenticatedAppWhatsappRouteRoute: typeof AuthenticatedAppWhatsappRouteRoute
  AuthenticatedAppGroupOrdersGroupOrderIdRoute: typeof AuthenticatedAppGroupOrdersGroupOrderIdRoute
  AuthenticatedAdminActivityLogIndexRoute: typeof AuthenticatedAdminActivityLogIndexRoute
  AuthenticatedAdminDashboardIndexRoute: typeof AuthenticatedAdminDashboardIndexRoute
  AuthenticatedAdminPendingIndexRoute: typeof AuthenticatedAdminPendingIndexRoute
  AuthenticatedAppAccountIndexRoute: typeof AuthenticatedAppAccountIndexRoute
  AuthenticatedAppAttendanceIndexRoute: typeof AuthenticatedAppAttendanceIndexRoute
  AuthenticatedAppBlocksIndexRoute: typeof AuthenticatedAppBlocksIndexRoute
  AuthenticatedAppCustomersIndexRoute: typeof AuthenticatedAppCustomersIndexRoute
  AuthenticatedAppDashboardIndexRoute: typeof AuthenticatedAppDashboardIndexRoute
  AuthenticatedAppEmployeesIndexRoute: typeof AuthenticatedAppEmployeesIndexRoute
  AuthenticatedAppGroupOrdersIndexRoute: typeof AuthenticatedAppGroupOrdersIndexRoute
  AuthenticatedAppOrdersIndexRoute: typeof AuthenticatedAppOrdersIndexRoute
  AuthenticatedAppProfileIndexRoute: typeof AuthenticatedAppProfileIndexRoute
  AuthenticatedAppRolePermissionIndexRoute: typeof AuthenticatedAppRolePermissionIndexRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
  AuthenticatedAppSupportIndexRoute: typeof AuthenticatedAppSupportIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppCategoryRouteRoute: AuthenticatedAppCategoryRouteRoute,
  AuthenticatedAppMeasurementsRouteRoute:
    AuthenticatedAppMeasurementsRouteRoute,
  AuthenticatedAppUsersRouteRoute: AuthenticatedAppUsersRouteRoute,
  AuthenticatedAppWhatsappRouteRoute: AuthenticatedAppWhatsappRouteRoute,
  AuthenticatedAppGroupOrdersGroupOrderIdRoute:
    AuthenticatedAppGroupOrdersGroupOrderIdRoute,
  AuthenticatedAdminActivityLogIndexRoute:
    AuthenticatedAdminActivityLogIndexRoute,
  AuthenticatedAdminDashboardIndexRoute: AuthenticatedAdminDashboardIndexRoute,
  AuthenticatedAdminPendingIndexRoute: AuthenticatedAdminPendingIndexRoute,
  AuthenticatedAppAccountIndexRoute: AuthenticatedAppAccountIndexRoute,
  AuthenticatedAppAttendanceIndexRoute: AuthenticatedAppAttendanceIndexRoute,
  AuthenticatedAppBlocksIndexRoute: AuthenticatedAppBlocksIndexRoute,
  AuthenticatedAppCustomersIndexRoute: AuthenticatedAppCustomersIndexRoute,
  AuthenticatedAppDashboardIndexRoute: AuthenticatedAppDashboardIndexRoute,
  AuthenticatedAppEmployeesIndexRoute: AuthenticatedAppEmployeesIndexRoute,
  AuthenticatedAppGroupOrdersIndexRoute: AuthenticatedAppGroupOrdersIndexRoute,
  AuthenticatedAppOrdersIndexRoute: AuthenticatedAppOrdersIndexRoute,
  AuthenticatedAppProfileIndexRoute: AuthenticatedAppProfileIndexRoute,
  AuthenticatedAppRolePermissionIndexRoute:
    AuthenticatedAppRolePermissionIndexRoute,
  AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
  AuthenticatedAppSupportIndexRoute: AuthenticatedAppSupportIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R403Route: R403Route,
  authActivateAccountRoute: authActivateAccountRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
